MOVIES_DETAILS_WITH_CAST_IDS = [
    {
        "id": 1893,
        "title": "Star Wars: Episode I - The Phantom Menace",
        "tagline": "Every generation has a legend. Every journey has a first step. Every saga has a beginning.",
        "overview": "Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.",
        "popularity": 22.71543,
        "runtime": 136,
        "releaseDate": "1999-05-19",
        "revenue": 924317558,
        "budget": 115000000,
        "posterPath": "https://image.tmdb.org/t/p/w342/n8V09dDc02KsSN6Q4hC2BX6hN8X.jpg",
        "originalLanguage": "en",
        "genres": [12, 28, 878],
        "cast": [3896, 3061, 524, 33196, 27762, 6, 130],
    },
    {
        "id": 1724,
        "title": "The Incredible Hulk",
        "tagline": "You'll like him when he's angry.",
        "overview": "Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with a new, deadly foe.",
        "popularity": 22.619048,
        "runtime": 114,
        "releaseDate": "2008-06-12",
        "revenue": 163712074,
        "budget": 150000000,
        "posterPath": "https://image.tmdb.org/t/p/w342/bleR2qj9UluYl7x0Js7VXuLhV3s.jpg",
        "originalLanguage": "en",
        "genres": [878, 28, 12],
        "cast": [819, 882, 3129, 227, 1462, 15232, 68277],
    },
    {
        "id": 955,
        "title": "Mission: Impossible II",
        "tagline": "Expect the impossible again.",
        "overview": "With computer genius Luther Stickell at his side and a beautiful thief on his mind, agent Ethan Hunt races across Australia and Spain to stop a former IMF agent from unleashing a genetically engineered biological weapon called Chimera. This mission, should Hunt choose to accept it, plunges him into the center of an international crisis of terrifying magnitude.",
        "popularity": 22.556298,
        "runtime": 123,
        "releaseDate": "2000-05-24",
        "revenue": 546388105,
        "budget": 125000000,
        "posterPath": "https://image.tmdb.org/t/p/w342/eRaEC0vf5q5TSvaoJPwGTt2wa9T.jpg",
        "originalLanguage": "en",
        "genres": [12, 28, 53],
        "cast": [500, 15336, 9030, 10182, 12206, 15337, 2039],
    },
    {
        "id": 24,
        "title": "Kill Bill: Vol. 1",
        "tagline": "Go for the kill.",
        "overview": "An assassin is shot at the altar by her ruthless employer, Bill and other members of their assassination circle – but 'The Bride' lives to plot her vengeance. Setting out for some payback, she makes a death list and hunts down those who wronged her, saving Bill for last.",
        "popularity": 22.464692,
        "runtime": 111,
        "releaseDate": "2003-10-10",
        "revenue": 180949045,
        "budget": 30000000,
        "posterPath": "https://image.tmdb.org/t/p/w342/97fNAi62HawGjWru7PvVmF7RAbU.jpg",
        "originalLanguage": "en",
        "genres": [28, 80],
        "cast": [139, 140, 2535, 589, 141, 147, 2539],
    },
    {
        "id": 485942,
        "title": "Batman Ninja",
        "tagline": "",
        "overview": "«Batman Ninja» takes a journey across the ages as Gorilla Grodd's time displacement machine transports many of Batman's worst enemies to feudal Japan —along with the Dark Knight and a few of his allies. The villains take over the forms of the feudal lords that rule the divided land, with the Joker taking the lead among the warring factions. As his traditional high-tech weaponry is exhausted almost immediately, Batman must rely on his intellect and his allies —including Catwoman and the extended Bat-family— to restore order to the land, and return to present-day Gotham City.",
        "popularity": 24.193477,
        "runtime": 85,
        "releaseDate": "2018-04-24",
        "revenue": 0,
        "budget": 0,
        "posterPath": "https://image.tmdb.org/t/p/w342/kZIrg87DiU1xKqCNcEV6LMfj3pS.jpg",
        "originalLanguage": "ja",
        "genres": [28, 16],
        "cast": [20664, 112278, 83928, 1324646, 552683, 1241498, 81244],
    },
]

MOVIES_DETAILS_COMPLETED = [
    {
        "id": 1893,
        "title": "Star Wars: Episode I - The Phantom Menace",
        "tagline": "Every generation has a legend. Every journey has a first step. Every saga has a beginning.",
        "overview": "Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.",
        "popularity": 22.71543,
        "runtime": 136,
        "releaseDate": "1999-05-19",
        "revenue": 924317558,
        "budget": 115000000,
        "posterPath": "https://image.tmdb.org/t/p/w342/n8V09dDc02KsSN6Q4hC2BX6hN8X.jpg",
        "originalLanguage": "en",
        "genres": [12, 28, 878],
        "cast": [
            {
                "id": "3896",
                "name": "Liam Neeson",
                "profilePath": "https://image.tmdb.org/t/p/w185/9mdAohLsDu36WaXV2N3SQ388bvz.jpg",
                "gender": 2,
                "movies": [1893, 241554, 272, 260346, 399035],
            },
            {
                "id": "3061",
                "name": "Ewan McGregor",
                "profilePath": "https://image.tmdb.org/t/p/w185/aEmyadfRXTmmR7UW7OXsm5a6smS.jpg",
                "gender": 2,
                "movies": [1893, 321612],
            },
            {
                "id": "524",
                "name": "Natalie Portman",
                "profilePath": "https://image.tmdb.org/t/p/w185/rtLTG4yrEcROXhTBGXMrbyiUEC5.jpg",
                "gender": 1,
                "movies": [1893, 101, 76338, 10195, 300668],
            },
            {
                "id": "33196",
                "name": "Jake Lloyd",
                "profilePath": "https://image.tmdb.org/t/p/w185/1MndIkdjjDypRDi3PpMzy3j0Lof.jpg",
                "gender": 2,
                "movies": [1893],
            },
            {
                "id": "27762",
                "name": "Ian McDiarmid",
                "profilePath": "https://image.tmdb.org/t/p/w185/sa6FTcK7xCHCFFR10jyOOOffd7f.jpg",
                "gender": 2,
                "movies": [1893],
            },
            {
                "id": "6",
                "name": "Anthony Daniels",
                "profilePath": "https://image.tmdb.org/t/p/w185/cljvryjb3VwTsNR7fjQKjNPMaBB.jpg",
                "gender": 2,
                "movies": [1893, 11],
            },
            {
                "id": "130",
                "name": "Kenny Baker",
                "profilePath": "https://image.tmdb.org/t/p/w185/sdd9rgifNF9C51RejG7sUGU8Bka.jpg",
                "gender": 2,
                "movies": [1893, 11],
            },
        ],
    },
    {
        "id": 1724,
        "title": "The Incredible Hulk",
        "tagline": "You'll like him when he's angry.",
        "overview": "Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with a new, deadly foe.",
        "popularity": 22.619048,
        "runtime": 114,
        "releaseDate": "2008-06-12",
        "revenue": 163712074,
        "budget": 150000000,
        "posterPath": "https://image.tmdb.org/t/p/w342/bleR2qj9UluYl7x0Js7VXuLhV3s.jpg",
        "originalLanguage": "en",
        "genres": [878, 28, 12],
        "cast": [
            {
                "id": "819",
                "name": "Edward Norton",
                "profilePath": "https://image.tmdb.org/t/p/w185/eIkFHNlfretLS1spAcIoihKUS62.jpg",
                "gender": 2,
                "movies": [1724, 399174, 194662, 550],
            },
            {
                "id": "882",
                "name": "Liv Tyler",
                "profilePath": "https://image.tmdb.org/t/p/w185/lD2YnrKdnRUvFDMSiK2pw13ZMIB.jpg",
                "gender": 1,
                "movies": [1724, 121, 122, 120],
            },
            {
                "id": "3129",
                "name": "Tim Roth",
                "profilePath": "https://image.tmdb.org/t/p/w185/hgaIXIW9GKnZhrweplBonG7uhhP.jpg",
                "gender": 2,
                "movies": [1724],
            },
            {
                "id": "227",
                "name": "William Hurt",
                "profilePath": "https://image.tmdb.org/t/p/w185/zp6UOht6c1iyHDbpYn1hkX103lG.jpg",
                "gender": 2,
                "movies": [1724],
            },
            {
                "id": "1462",
                "name": "Tim Blake Nelson",
                "profilePath": "https://image.tmdb.org/t/p/w185/tWHHEnnoEU6aNaiFRvl1WLfNTvB.jpg",
                "gender": 2,
                "movies": [1724],
            },
            {
                "id": "15232",
                "name": "Ty Burrell",
                "profilePath": "https://image.tmdb.org/t/p/w185/hJeOomahu5I7CgODCU9jh7oPsu6.jpg",
                "gender": 2,
                "movies": [1724],
            },
            {
                "id": "68277",
                "name": "Christina Cabot",
                "profilePath": "https://image.tmdb.org/t/p/w185/7UBTv5lW6apPdVLnOqTTBMTJWwY.jpg",
                "gender": 1,
                "movies": [1724],
            },
        ],
    },
    {
        "id": 955,
        "title": "Mission: Impossible II",
        "tagline": "Expect the impossible again.",
        "overview": "With computer genius Luther Stickell at his side and a beautiful thief on his mind, agent Ethan Hunt races across Australia and Spain to stop a former IMF agent from unleashing a genetically engineered biological weapon called Chimera. This mission, should Hunt choose to accept it, plunges him into the center of an international crisis of terrifying magnitude.",
        "popularity": 22.556298,
        "runtime": 123,
        "releaseDate": "2000-05-24",
        "revenue": 546388105,
        "budget": 125000000,
        "posterPath": "https://image.tmdb.org/t/p/w342/eRaEC0vf5q5TSvaoJPwGTt2wa9T.jpg",
        "originalLanguage": "en",
        "genres": [12, 28, 53],
        "cast": [
            {
                "id": "500",
                "name": "Tom Cruise",
                "profilePath": "https://image.tmdb.org/t/p/w185/3oWEuo0e8Nx8JvkqYCDec2iMY6K.jpg",
                "gender": 2,
                "movies": [955, 954, 177677],
            },
            {
                "id": "15336",
                "name": "Dougray Scott",
                "profilePath": "https://image.tmdb.org/t/p/w185/zeZmtK4EKK9R2r6bp2nTxMs3ByS.jpg",
                "gender": 2,
                "movies": [955, 45054, 260346],
            },
            {
                "id": "9030",
                "name": "Thandie Newton",
                "profilePath": "https://image.tmdb.org/t/p/w185/sW6XsnM2DkX6ujOXZ38aIQAMIWi.jpg",
                "gender": 1,
                "movies": [955, 348350],
            },
            {
                "id": "10182",
                "name": "Ving Rhames",
                "profilePath": "https://image.tmdb.org/t/p/w185/8nS83GOu0iqxjL2Oj2DgwkAceFQ.jpg",
                "gender": 2,
                "movies": [680, 955, 954, 177677],
            },
            {
                "id": "12206",
                "name": "Richard Roxburgh",
                "profilePath": "https://image.tmdb.org/t/p/w185/hN1bWQ0Qe0DrA33Ch6TLKuIWs0.jpg",
                "gender": 2,
                "movies": [955],
            },
            {
                "id": "15337",
                "name": "John Polson",
                "profilePath": "https://image.tmdb.org/t/p/w185/rsjpQFAvQSo05HflPSCODCCbYFl.jpg",
                "gender": 2,
                "movies": [955],
            },
            {
                "id": "2039",
                "name": "Brendan Gleeson",
                "profilePath": "https://image.tmdb.org/t/p/w185/pUTBk2sqFgg4aFBXHckD0qKLUYP.jpg",
                "gender": 2,
                "movies": [955],
            },
        ],
    },
    {
        "id": 24,
        "title": "Kill Bill: Vol. 1",
        "tagline": "Go for the kill.",
        "overview": "An assassin is shot at the altar by her ruthless employer, Bill and other members of their assassination circle – but 'The Bride' lives to plot her vengeance. Setting out for some payback, she makes a death list and hunts down those who wronged her, saving Bill for last.",
        "popularity": 22.464692,
        "runtime": 111,
        "releaseDate": "2003-10-10",
        "revenue": 180949045,
        "budget": 30000000,
        "posterPath": "https://image.tmdb.org/t/p/w342/97fNAi62HawGjWru7PvVmF7RAbU.jpg",
        "originalLanguage": "en",
        "genres": [28, 80],
        "cast": [
            {
                "id": "139",
                "name": "Uma Thurman",
                "profilePath": "https://image.tmdb.org/t/p/w185/43DjE9bGtR8z7ejCRvf2tPXPpm1.jpg",
                "gender": 1,
                "movies": [680, 24],
            },
            {
                "id": "140",
                "name": "Lucy Liu",
                "profilePath": "https://image.tmdb.org/t/p/w185/9nbtjqsx3De7hO2XDtrBQ7M9VCH.jpg",
                "gender": 1,
                "movies": [24],
            },
            {
                "id": "2535",
                "name": "Vivica A. Fox",
                "profilePath": "https://image.tmdb.org/t/p/w185/uxTOzgRhk0VkbK1ZiOrQSTYuzAl.jpg",
                "gender": 1,
                "movies": [24],
            },
            {
                "id": "589",
                "name": "Daryl Hannah",
                "profilePath": "https://image.tmdb.org/t/p/w185/4LLmp6AQdlj6ueGCRbVRSGvvFSt.jpg",
                "gender": 1,
                "movies": [78, 24],
            },
            {
                "id": "141",
                "name": "David Carradine",
                "profilePath": "https://image.tmdb.org/t/p/w185/wCvrY9PUKtN6NwkmLHWLJivCCov.jpg",
                "gender": 2,
                "movies": [24],
            },
            {
                "id": "147",
                "name": "Michael Madsen",
                "profilePath": "https://image.tmdb.org/t/p/w185/azCognW0p1hl2bJFH31ZNtcTJ3R.jpg",
                "gender": 2,
                "movies": [24],
            },
            {
                "id": "2539",
                "name": "Julie Dreyfus",
                "profilePath": "https://image.tmdb.org/t/p/w185/vkUvcV6oFkZXcIv4SGeW66LUoqC.jpg",
                "gender": 1,
                "movies": [24],
            },
        ],
    },
    {
        "id": 485942,
        "title": "Batman Ninja",
        "tagline": "",
        "overview": "«Batman Ninja» takes a journey across the ages as Gorilla Grodd's time displacement machine transports many of Batman's worst enemies to feudal Japan —along with the Dark Knight and a few of his allies. The villains take over the forms of the feudal lords that rule the divided land, with the Joker taking the lead among the warring factions. As his traditional high-tech weaponry is exhausted almost immediately, Batman must rely on his intellect and his allies —including Catwoman and the extended Bat-family— to restore order to the land, and return to present-day Gotham City.",
        "popularity": 24.193477,
        "runtime": 85,
        "releaseDate": "2018-04-24",
        "revenue": 0,
        "budget": 0,
        "posterPath": "https://image.tmdb.org/t/p/w342/kZIrg87DiU1xKqCNcEV6LMfj3pS.jpg",
        "originalLanguage": "ja",
        "genres": [28, 16],
        "cast": [
            {
                "id": "20664",
                "name": "Kouichi Yamadera",
                "profilePath": "https://image.tmdb.org/t/p/w185/m5su8OKD2rZn9XWJfh8aPC403Nz.jpg",
                "gender": 2,
                "movies": [485942],
            },
            {
                "id": "112278",
                "name": "Wataru Takagi",
                "profilePath": "https://image.tmdb.org/t/p/w185/j0mQoLTEwzWYoJTsPtl9X25V43R.jpg",
                "gender": 2,
                "movies": [485942],
            },
            {
                "id": "83928",
                "name": "Rie Kugimiya",
                "profilePath": "https://image.tmdb.org/t/p/w185/4k7CLf1yPWtwZRkieAPYuKzEl3L.jpg",
                "gender": 1,
                "movies": [485942],
            },
            {
                "id": "1324646",
                "name": "Ai Kakuma",
                "profilePath": "https://image.tmdb.org/t/p/w185/g7vys7fqqdn40ePXQgx3XWinxtw.jpg",
                "gender": 1,
                "movies": [485942],
            },
            {
                "id": "552683",
                "name": "Hōchū Ōtsuka",
                "profilePath": "https://image.tmdb.org/t/p/w185/9U0zHSf15fNqvMSImqCiIUnUBCk.jpg",
                "gender": 0,
                "movies": [485942],
            },
            {
                "id": "1241498",
                "name": "Daisuke Ono",
                "profilePath": "https://image.tmdb.org/t/p/w185/zVXEvZtCGRhOYFOoaA5m0ZGX9Ta.jpg",
                "gender": 2,
                "movies": [485942],
            },
            {
                "id": "81244",
                "name": "Akira Ishida",
                "profilePath": "https://image.tmdb.org/t/p/w185/jnW2Gn2NlR2uwOCeyOuzypnTmkH.jpg",
                "gender": 2,
                "movies": [485942],
            },
        ],
    },
]
